name: Test Stream

on:
  schedule:
    # 9:00 PM IST = 15:30 UTC (Sat)
    - cron: '30 15 24* * 6'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Verify video file
        run: |
          ls -lh
          ffmpeg -i test.mp4

      - name: Stream to YouTube
        run: |
         ffmpeg -re -stream_loop -1 -i test.mp4 -c:v libx264 -preset veryfast -pix_fmt yuv420p -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.TEST_KEY }}"
